approved = [
  "mit",
  "apache-2.0",
  "bsd-3-clause",
  "bsd-2-clause",
  "mpl-2.0",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "OpenSSL",
  "CC0-1.0",
]

ignored = [
  "buf.build/gen/go/agntcy/oasf/protocolbuffers/go",
  "buf.build/gen/go/agntcy/oasf-sdk/protocolbuffers/go",
  "buf.build/gen/go/agntcy/oasf-sdk/grpc/go",
  
  "google.golang.org/protobuf", # BSD-3-Clause https://github.com/protocolbuffers/protobuf-go/blob/master/LICENSE
]
