# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

vars:
  BIN_DIR: "{{ .ROOT_DIR }}/bin"
  GO_MOD_DIR:
    sh: find . -name go.mod -exec dirname {} \;
  HELM_CHART_OCI_REGISTRY: "oci://ghcr.io/agntcy/oasf-sdk/helm-charts"

  PROTOC_VERSION: "27.1"
  PROTOC_BIN: "{{ .BIN_DIR }}/protoc-{{.PROTOC_VERSION}}"
  BUFBUILD_VERSION: "1.50.1"
  BUFBUILD_BIN: "{{ .BIN_DIR }}/bufbuild-{{.BUFBUILD_VERSION}}"
  LICENSEI_VERSION: "0.9.0"
  LICENSEI_BIN: "{{ .BIN_DIR }}/licensei-{{.LICENSEI_VERSION}}"
  MULTIMOD_VERSION: "0.17.0"
  MULTIMOD_BIN: "{{ .BIN_DIR }}/multimod-{{.MULTIMOD_VERSION}}"
  GOLANGCI_LINT_VERSION: "2.6.1"
  GOLANGCI_LINT_BIN: "{{ .BIN_DIR }}/golangci-lint-{{.GOLANGCI_LINT_VERSION}}"
  HELM_VERSION: "3.16.3"
  HELM_BIN: "{{ .BIN_DIR }}/helm-{{.HELM_VERSION}}"

includes:
  e2e:
    taskfile: ./e2e/Taskfile.yaml
    dir: ./e2e

tasks:
  default:
    cmds:
      - task -l

  fmt:
    desc: Run formatters
    deps:
      - task: deps:protoc
      - task: deps:bufbuild
    dir: ./proto
    cmds:
      - "{{.BUFBUILD_BIN}} dep update"
      - "{{.BUFBUILD_BIN}} format --output ./"

  compile:
    desc: Compile binary for host platform
    dir: ./server
    vars:
      GOOS: "{{ .GOOS | default OS }}"
      GOARCH: "{{ .GOARCH | default ARCH }}"
      BINARY_NAME: '{{ .BINARY_NAME | default "oasf-sdk" }}'
      OUT_BINARY: '{{ .OUT_BINARY | default (printf "%s/%s" .BIN_DIR .BINARY_NAME) }}'
    cmds:
      - CGO_ENABLED=0 GOOS={{ .GOOS }} GOARCH={{ .GOARCH }} BINARY_NAME={{ .BINARY_NAME }} go build -ldflags="-s -w -extldflags -static" -o "{{ .OUT_BINARY }}" cmd/main.go

  compile:all:
    desc: Compile binary for multiple platforms
    cmds:
      - for:
          matrix:
            OS: ["linux", "darwin", "windows"]
            ARCH: ["amd64", "arm64"]
        cmd: |
          GOOS={{ .ITEM.OS }} GOARCH={{ .ITEM.ARCH }} BINARY_NAME=oasf-sdk-{{ .ITEM.OS }}-{{ .ITEM.ARCH }} BIN_DIR={{ .BIN_DIR }} task compile

  test:
    desc: Run Go unit tests for all modules (excludes e2e)
    vars:
      GO_MOD_DIR:
        sh: find . -name go.mod -not -path "./e2e/*" -exec dirname {} \;
    cmds:
      - for: { var: GO_MOD_DIR }
        cmd: echo "Running tests in {{.ITEM}}" && cd {{.ITEM}} && go test -v ./...

  build:
    desc: Build image for host platform
    cmds:
      - docker buildx bake --set *.platform=linux/{{ ARCH }}

  build:all:
    desc: Build image for multiple platforms
    cmds:
      - docker buildx bake

  ##
  ## Linting
  ##
  lint:golangci-lint:
    desc: Run golangci-lint
    deps:
      - task: deps:golangci-lint
    vars:
      FIX: '{{ .FIX | default "false" }}'
      FIX_FLAG: '{{if eq .FIX "true"}}--fix{{end}}'
    cmds:
      - for: { var: GO_MOD_DIR }
        cmd: |
          echo "Running golangci-lint in {{.ITEM}}"
          cd {{.ITEM}}
          {{.GOLANGCI_LINT_BIN}} run --config {{.ROOT_DIR}}/.golangci.yml {{.FIX_FLAG}}

  lint:buf:
    desc: Run Buf linters
    deps:
      - task: deps:protoc
      - task: deps:bufbuild
    dir: ./proto
    cmds:
      - "{{.BUFBUILD_BIN}} lint"

  lint:
    desc: Run all linters
    deps:
      - task: lint:buf
      - task: lint:golangci-lint

  ##
  ## Release
  ##
  release:verify:
    desc: Verify release readiness
    deps:
      - task: deps:multimod-bin
    cmds:
      - "{{ .MULTIMOD_BIN }} verify"

  release:prepare:
    desc: Prepare release
    deps:
      - task: deps:multimod-bin
    cmds:
      - "{{ .MULTIMOD_BIN }} prerelease --all-module-sets --skip-go-mod-tidy=true --commit-to-different-branch=false"
      - git commit --amend --signoff --no-edit

  ##
  ## Helm
  ##
  helm:dependency-update:
    desc: Update Helm chart dependencies
    deps:
      - task: deps:helm
    cmds:
      - cmd: echo "Updating Helm chart dependencies..."
      - cmd: "{{ .HELM_BIN }} dependency update helm/oasf-sdk"

  helm:lint:
    desc: Lint Helm chart
    deps:
      - task: deps:helm
    cmds:
      - cmd: echo "Linting Helm chart..."
      - cmd: "{{ .HELM_BIN }} lint helm/oasf-sdk --with-subcharts"

  helm:package:
    desc: Package Helm chart
    deps:
      - task: deps:helm
    vars:
      VERSION: '{{ .VERSION | default "0.0.1-dev" }}'
    cmds:
      - cmd: echo "Packaging Helm chart version {{.VERSION}}"
      - cmd: "{{ .HELM_BIN }} package helm/oasf-sdk --dependency-update --version {{ .VERSION }}"
      - cmd: echo "Chart packaged successfully as oasf-sdk-{{.VERSION}}.tgz"

  helm:push:
    desc: Push Helm chart to OCI registry
    deps:
      - task: deps:helm
    vars:
      VERSION: '{{ .VERSION | default "0.0.1-dev" }}'
    preconditions:
      - sh: test -f oasf-sdk-{{.VERSION}}.tgz
        msg: "Chart package oasf-sdk-{{.VERSION}}.tgz not found. Run 'task helm:package VERSION={{.VERSION}}' first."
    cmds:
      - cmd: echo "Pushing oasf-sdk-{{.VERSION}}.tgz to {{ .HELM_CHART_OCI_REGISTRY }}"
      - cmd: "{{ .HELM_BIN }} push oasf-sdk-{{.VERSION}}.tgz {{ .HELM_CHART_OCI_REGISTRY }}"
      - cmd: echo "Chart pushed successfully to {{ .HELM_CHART_OCI_REGISTRY }}"

  ##
  ## License
  ##
  license:
    desc: Check all license compliance (headers and dependencies)
    deps:
      - task: deps:licensei
    cmds:
      - task: license:header
      - task: license:check

  license:header:
    desc: Check license headers in source files
    deps:
      - task: deps:licensei
    cmds:
      - cmd: echo "Checking license headers in source files" && {{ .LICENSEI_BIN }} header --config .licensei.toml

  license:check:
    desc: Check licenses of dependencies
    deps:
      - task: deps:licensei
    cmds:
      - cmd: echo "Checking dependency licenses" && {{ .LICENSEI_BIN }} check --config .licensei.toml

  license:cache:
    desc: Cache licenses of dependencies
    deps:
      - task: deps:licensei
    cmds:
      - for: { var: GO_MOD_DIR }
        cmd: echo "Caching licenses in {{.ITEM}}" && cd {{.ITEM}} && {{ .LICENSEI_BIN }} cache --config {{.ROOT_DIR}}/.licensei.toml

  ##
  ## Dependencies
  ##
  deps:tidy:
    desc: Ensure dependencies are up-to-date
    cmds:
      - for: { var: GO_MOD_DIR }
        cmd: go -C {{.ITEM}} mod tidy -go={{.GO_VERSION}}

  deps:bin-dir:
    desc: Create bin directory
    internal: true
    run: once
    cmd: mkdir -p {{.BIN_DIR}}
    status:
      - test -d {{.BIN_DIR}}

  deps:protoc:
    desc: Ensure supported Protoc version and plugins are installed
    internal: true
    deps:
      - deps:bin-dir
    preconditions:
      - which go
      - which curl
      - which unzip
    vars:
      ARCH_TYPE: '{{ if eq ARCH "arm64" }}aarch_64{{ else if eq ARCH "amd64" }}x86_64{{else if eq ARCH "s390x"}}x390_64{{ else }}{{ARCH}}{{ end }}'
      OS_VARIANT: '{{ if eq OS "darwin" }}osx-universal_binary{{ else if eq OS "windows" }}win64{{else}}linux-{{.ARCH_TYPE}}{{ end }}'
    cmds:
      - cmd: echo "Downloading Protoc v{{.PROTOC_VERSION}}..."
      - cmd: |
          curl -sL https://github.com/protocolbuffers/protobuf/releases/download/v{{.PROTOC_VERSION}}/protoc-{{.PROTOC_VERSION}}-{{.OS_VARIANT}}.zip -o {{.BIN_DIR}}/tmp.zip
          unzip -j {{.BIN_DIR}}/tmp.zip "bin/protoc" -d {{.BIN_DIR}}
          mv {{.BIN_DIR}}/protoc {{.PROTOC_BIN}}
          rm {{.BIN_DIR}}/tmp.zip
      - cmd: chmod +x {{.PROTOC_BIN}}
      - cmd: echo "Downloading go plugins for protoc..."
      - cmd: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - cmd: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - cmd: go install github.com/NathanBaulch/protoc-gen-cobra@latest
    status:
      - test -x {{.PROTOC_BIN}}

  deps:bufbuild:
    desc: Ensure supported bufbuild version is installed
    internal: true
    deps:
      - deps:bin-dir
    preconditions:
      - which curl
    vars:
      ARCH_TYPE: '{{ if eq ARCH "amd64" }}x86_64{{ else }}{{ARCH}}{{ end }}'
    cmds:
      - cmd: echo "Downloading BufBuild v{{.BUFBUILD_VERSION}}..."
      - cmd: |
          curl -L "https://github.com/bufbuild/buf/releases/download/v{{.BUFBUILD_VERSION}}/buf-{{OS}}-{{.ARCH_TYPE}}" -o {{.BUFBUILD_BIN}}
      - cmd: chmod +x {{.BUFBUILD_BIN}}
    status:
      - test -x {{.BUFBUILD_BIN}}

  deps:licensei:
    desc: Install licensei
    internal: true
    deps:
      - deps:bin-dir
    cmds:
      - curl -sfL https://raw.githubusercontent.com/goph/licensei/master/install.sh | bash -s v{{.LICENSEI_VERSION}}
      - mv {{.BIN_DIR}}/licensei {{.LICENSEI_BIN}}
      - chmod +x {{.LICENSEI_BIN}}
    status:
      - test -x {{.LICENSEI_BIN}}

  deps:multimod-bin:
    desc: Build the multimod binary
    internal: true
    deps:
      - deps:bin-dir
    vars:
      MULTIMOD_REPO_DIR: "{{ .BIN_DIR }}/opentelemetry-go-build-tools"
    cmds:
      - git clone https://github.com/open-telemetry/opentelemetry-go-build-tools --branch multimod/v{{.MULTIMOD_VERSION}} {{.MULTIMOD_REPO_DIR}}
      - go build -C {{.MULTIMOD_REPO_DIR}}/multimod -o {{.MULTIMOD_BIN}} main.go
      - rm -rf {{.MULTIMOD_REPO_DIR}}
    status:
      - test -x {{.MULTIMOD_BIN}}

  deps:golangci-lint:
    desc: Install golangci-lint
    internal: true
    deps:
      - deps:bin-dir
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s v{{.GOLANGCI_LINT_VERSION}}
      - mv {{.BIN_DIR}}/golangci-lint {{.GOLANGCI_LINT_BIN}}
      - chmod +x {{.GOLANGCI_LINT_BIN}}
    status:
      - test -x {{.GOLANGCI_LINT_BIN}}

  deps:helm:
    desc: Ensure supported Helm version is installed
    internal: true
    deps:
      - deps:bin-dir
    preconditions:
      - which curl
      - which tar
    cmds:
      - echo "Downloading Helm v{{.HELM_VERSION}}..."
      - curl -sSfL 'https://get.helm.sh/helm-v{{.HELM_VERSION}}-{{OS}}-{{ARCH}}.tar.gz' --output - | tar xzvOf - '{{OS}}-{{ARCH}}/helm' > {{.HELM_BIN}}
      - chmod +x {{.HELM_BIN}}
    status:
      - test -x {{.HELM_BIN}}
