# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

vars:
  BIN_DIR: '{{ .ROOT_DIR }}/bin'
  PROTOC_VERSION: '27.1'
  PROTOC_BIN: '{{ .BIN_DIR }}/protoc-{{.PROTOC_VERSION}}'
  BUFBUILD_VERSION: '1.50.1'
  BUFBUILD_BIN: '{{ .BIN_DIR }}/bufbuild-{{.BUFBUILD_VERSION}}'
  LICENSEI_VERSION: '0.9.0'
  LICENSEI_BIN: '{{ .BIN_DIR }}/licensei-{{.LICENSEI_VERSION}}'

includes:
  translation:
    taskfile: ./translation/Taskfile.yml
    dir: ./translation
    vars:
      BIN_DIR: '{{ .BIN_DIR }}'
  validation:
    taskfile: ./validation/Taskfile.yml
    dir: ./validation
    vars:
      BIN_DIR: '{{ .BIN_DIR }}'

tasks:
  default:
    cmds:
      - task -l

  fmt:
    desc: Run formatters
    deps:
      - task: deps:protoc
      - task: deps:bufbuild
    dir: ./proto
    cmds:
      - '{{.BUFBUILD_BIN}} dep update'
      - '{{.BUFBUILD_BIN}} format --output ./'

  lint:
    desc: Run linters
    deps:
      - task: deps:protoc
      - task: deps:bufbuild
    dir: ./proto
    cmds:
      - '{{.BUFBUILD_BIN}} dep update'
      - '{{.BUFBUILD_BIN}} format --diff --exit-code'
      - '{{.BUFBUILD_BIN}} lint'

  compile:
    desc: Compile binaries for all components
    cmds:
      - task translation:compile
      - task validation:compile

  compile:all:
    desc: Compile binaries for all components for all platforms
    cmds:
      - task translation:compile:all
      - task validation:compile:all

  build:
    desc: Build images for all components
    cmds:
      - task translation:build
      - task validation:build

  build:all:
    desc: Build images for all components for all platforms
    cmds:
      - task translation:build:all
      - task validation:build:all

  ##
  ## Test
  ##
  test:e2e:
    desc: Run end-to-end tests
    dir: e2e
    cmds:
      - go mod tidy
      - go test ./... -v

  test:e2e:setup:
    desc: Ensure dependencies for e2e tests are up-to-date
    dir: e2e
    cmds:
      - |
        docker run -d \
          --name translation-e2e \
          -p 31234:31234 \
          -e TRANSLATION_SERVER_LISTEN_ADDRESS=0.0.0.0:31234 \
          oasf-sdk-translation

        # Start validation service
        docker run -d \
          --name validation-e2e \
          -p 31235:31235 \
          -e VALIDATION_SERVER_LISTEN_ADDRESS=0.0.0.0:31235 \
          oasf-sdk-validation

  test:e2e:destroy:
    desc: Ensure dependencies for e2e tests are up-to-date
    dir: e2e
    cmds:
      - |
        docker stop translation-e2e
        docker stop validation-e2e
        docker rm translation-e2e
        docker rm validation-e2e

  ##
  ## Dependencies
  ##
  deps:tidy:
    desc: Ensure dependencies are up-to-date
    vars:
      GO_MOD_DIR:
        sh: find . -name go.mod -exec dirname {} \;
    cmds:
      - for: { var: GO_MOD_DIR }
        cmd: go -C {{.ITEM}} mod tidy -go={{.GO_VERSION}}

  deps:bin-dir:
    desc: Create bin directory
    internal: true
    run: once
    cmd: mkdir -p {{.BIN_DIR}}
    status:
      - test -d {{.BIN_DIR}}

  deps:protoc:
    desc: Ensure supported Protoc version and plugins are installed
    internal: true
    deps:
      - deps:bin-dir
    preconditions:
      - which go
      - which curl
      - which unzip
    vars:
      ARCH_TYPE: '{{ if eq ARCH "arm64" }}aarch_64{{ else if eq ARCH "amd64" }}x86_64{{else if eq ARCH "s390x"}}x390_64{{ else }}{{ARCH}}{{ end }}'
      OS_VARIANT: '{{ if eq OS "darwin" }}osx-universal_binary{{ else if eq OS "windows" }}win64{{else}}linux-{{.ARCH_TYPE}}{{ end }}'
    cmds:
      - cmd: echo "Downloading Protoc v{{.PROTOC_VERSION}}..."
      - cmd: |
          curl -sL https://github.com/protocolbuffers/protobuf/releases/download/v{{.PROTOC_VERSION}}/protoc-{{.PROTOC_VERSION}}-{{.OS_VARIANT}}.zip -o {{.BIN_DIR}}/tmp.zip
          unzip -j {{.BIN_DIR}}/tmp.zip "bin/protoc" -d {{.BIN_DIR}}
          mv {{.BIN_DIR}}/protoc {{.PROTOC_BIN}}
          rm {{.BIN_DIR}}/tmp.zip
      - cmd: chmod +x {{.PROTOC_BIN}}
      - cmd: echo "Downloading go plugins for protoc..."
      - cmd: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - cmd: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - cmd: go install github.com/NathanBaulch/protoc-gen-cobra@latest
    status:
      - test -x {{.PROTOC_BIN}}

  deps:bufbuild:
    desc: Ensure supported bufbuild version is installed
    internal: true
    deps:
      - deps:bin-dir
    preconditions:
      - which curl
    vars:
      ARCH_TYPE: '{{ if eq ARCH "amd64" }}x86_64{{ else }}{{ARCH}}{{ end }}'
    cmds:
      - cmd: echo "Downloading BufBuild v{{.BUFBUILD_VERSION}}..."
      - cmd: |
          curl -L "https://github.com/bufbuild/buf/releases/download/v{{.BUFBUILD_VERSION}}/buf-{{OS}}-{{.ARCH_TYPE}}" -o {{.BUFBUILD_BIN}}
      - cmd: chmod +x {{.BUFBUILD_BIN}}
    status:
      - test -x {{.BUFBUILD_BIN}}

  deps:licensei:
    desc: Install licensei
    internal: true
    deps:
      - deps:bin-dir
    cmds:
      - curl -sfL https://raw.githubusercontent.com/goph/licensei/master/install.sh | bash -s v{{.LICENSEI_VERSION}}
      - mv {{.BIN_DIR}}/licensei {{.LICENSEI_BIN}}
      - chmod +x {{.LICENSEI_BIN}}
    status:
      - test -x {{.LICENSEI_BIN}}

  ##
  ## License
  ##
  license:
    desc: Check all license compliance (headers and dependencies)
    deps:
      - task: deps:licensei
    cmds:
      - task: license:header
      - task: license:check

  license:header:
    desc: Check license headers in source files
    deps:
      - task: deps:licensei
    cmds:
      - cmd: echo "Checking license headers in source files" && {{ .LICENSEI_BIN }} header --config .licensei.toml

  license:check:
    desc: Check licenses of dependencies
    deps:
      - task: deps:licensei
    cmds:
      - cmd: echo "Checking dependency licenses" && {{ .LICENSEI_BIN }} check --config .licensei.toml

  license:cache:
    desc: Cache licenses of dependencies
    deps:
      - task: deps:licensei
    vars:
      GO_MOD_DIR:
        sh: find . -name go.mod -exec dirname {} \;
    cmds:
      - for: { var: GO_MOD_DIR }
        cmd: echo "Caching licenses in {{.ITEM}}" && cd {{.ITEM}} && {{ .LICENSEI_BIN }} cache --config {{.ROOT_DIR}}/.licensei.toml
