apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: '{{ .Release.Namespace }}'
  labels:
    helm.sh/chart: {{ template "oasf-sdk.chart" . }}
    app.kubernetes.io/name: {{ template "oasf-sdk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
