apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "oasf-sdk.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "oasf-sdk.chart" . }}
    app.kubernetes.io/name: {{ template "oasf-sdk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "oasf-sdk.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "oasf-sdk.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "oasf-sdk.serviceAccountName" . }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ include "oasf-sdk.version" . }}"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
                {{- if .Values.externalSecrets }}
            - secretRef:
                name: {{ .Release.Name }}-secrets
                {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: {{ .Values.service.internalPort }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
