# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

tasks:
  compile:
    desc: Compile Validation SDK to host platform
    vars:
      GOOS: '{{ .GOOS | default OS }}'
      GOARCH: '{{ .GOARCH | default ARCH }}'
      BINARY_NAME: '{{ .BINARY_NAME | default "oasfv" }}'
      OUT_BINARY: '{{ .OUT_BINARY | default (printf "%s/%s" .BIN_DIR .BINARY_NAME) }}'
    cmds:
      - CGO_ENABLED=0 GOOS={{ .GOOS }} GOARCH={{ .GOARCH }} BINARY_NAME={{ .BINARY_NAME }} go build -ldflags="-s -w -extldflags -static" -o "{{ .OUT_BINARY }}" cmd/main.go

  compile:all:
    desc: Compile Validation SDK binaries for multiple platforms
    cmds:
      - for:
          matrix:
            OS: ['linux', 'darwin']
            ARCH: ['amd64', 'arm64']
        cmd: |
          GOOS={{ .ITEM.OS }} GOARCH={{ .ITEM.ARCH }} BINARY_NAME=oasfv-{{ .ITEM.OS }}-{{ .ITEM.ARCH }} BIN_DIR={{ .BIN_DIR }} task compile

  build:
    desc: Build Validation SDK image
    dir: '{{ .ROOT_DIR }}'
    cmds:
      - docker buildx bake --set *.platform=linux/{{ ARCH }} validation

  build:all:
    desc: Build Validation SDK image for all platforms
    dir: '{{ .ROOT_DIR }}'
    cmds:
      - docker buildx bake validation
