# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: E2E Tests

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:g
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Set image tag
        id: tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Docker Images with commit tag
        run: |
          docker buildx bake \
            --set "oasf-sdk-e2e.tags=oasf-sdk:${{ steps.tag.outputs.IMAGE_TAG }}" \
            oasf-sdk-e2e --load

      - name: Start test containers
        run: |
          # Start translation service  
          docker run -d \
            --name oasf-sdk \
            -p 31234:31234 \
            oasf-sdk:${{ steps.tag.outputs.IMAGE_TAG }}

          # Wait for services to be ready
          echo "Waiting for services to start..."
          sleep 10
          
          # Check if services are running
          docker logs oasf-sdk

      - name: Run E2E Tests
        run: |
          task test:e2e

      - name: Show container logs on failure
        if: failure()
        run: |
          echo "=== OASF SDK Logs ==="
          docker logs oasf-sdk || true
