# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: E2E Tests

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Set image tag
        id: tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Docker Images with commit tag
        run: |
          task build:all

      - name: Tag images for e2e tests
        run: |
          docker tag oasf-sdk oasf-sdk:${{ steps.tag.outputs.IMAGE_TAG }}

      - name: Run E2E Tests
        run: |
          task test:e2e

      - name: Show container logs on failure
        if: failure()
        run: |
          echo "=== Container Logs ==="
          docker logs oasf-sdk || true
