# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: License check

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:  
  license:
    name: License
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Setup license cache
        uses: actions/cache@v4.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: |
            **/.licensei.cache
          key: license-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            license-cache-${{ runner.os }}-

      - name: License cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          task license:cache

      - name: License
        run: |
          task license
