# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Release pipeline

on:
  push:
    branches:
      - ci/release-pipeline
    tags:
      - "v*.*.*"

jobs:
  translation:
    name: Build Translation SDK binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Build
        run: |
          task translation:compile:all

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: binaries
          path: bin
          if-no-files-found: error

  release:
    name: Release
    needs:
      - translation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success:
    name: Success
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Echo Success
        run: echo "::notice Success!"
