# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Release pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  translation-binary:
    name: Build Translation SDK binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Build
        run: |
          task translation:compile:all

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: binaries
          path: bin
          if-no-files-found: error

  docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/bake-action@v4
        with:
          files: docker-bake.hcl
          targets: translation
          push: true
          set: |
            *.tags=ghcr.io/${{ github.repository_owner }}/oasf-sdk:${{ env.TAG }}
            *.tags=ghcr.io/${{ github.repository_owner }}/oasf-sdk:latest

  release:
    name: Release
    needs:
      - translation-binary
      - docker-image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

